### ISSUE TITLE
Support for other guards than "api" with hashed token

### ISSUE THREAD

**Issue by krychu90** [Livijn/multiple-tokens-auth#2]
When I have hashed tokens with other auth guard than "api" it will generate non hashed tokens because generateApiToken read "api" guard config.

Maybe It should read from new config in multiple-tokens-auth config file? Or read from proper guard.

**Comment by Livijn** [comment]
What guard are you using?

I can add an option to the config file for hashing as well.

**Comment by krychu90** [comment]
Hi,
I use a custom guard.

It can be config or attribute in the user model (if exists).

**Comment by Livijn** [comment]
Fixed @ https://github.com/Livijn/multiple-tokens-auth/commit/bf300a23a499eb7962704beddcfe8560ca70bfbe
